In [1]:
import numpy as np

In [2]:
X_train = np.array([[1000.0, 2.0], [1500.0, 3.0]])

In [3]:
X_train

array([[1000.,    2.],
       [1500.,    3.]])

In [4]:
#grab all the rows of the first column
X_train[:,0]

array([1000., 1500.])

In [5]:
#grab all rows of the second column
X_train[:,1]

array([2., 3.])

In [10]:
#minimum value of the first column
np.min(X_train[:,0])
# X_train[:,0].min()

1000.0

In [12]:
#mean of the first column
np.mean(X_train[:,0])
# X_train[:,0].mean()

1250.0

In [29]:
#Obtain the minimum value and divide it by the range of the column
def max_min_s(X):
    return (X - X.min(axis=0)) / (X.max(axis=0) - X.min(axis=0))
    

In [30]:
max_min_s(X_train)

array([[0., 0.],
       [1., 1.]])

In [31]:
#Using sklearn's built in function for max_min_s
from sklearn import preprocessing

min_max_scaler = preprocessing.MinMaxScaler()
X_minmax = min_max_scaler.fit_transform(X_train)
X_minmax

array([[0., 0.],
       [1., 1.]])

In [35]:
#Calculate the value minus the mean, over the standard deviation
def standard_s(X):
    return (X - X.mean(axis=0)) / (X.std(axis=0))
    

In [36]:
standard_s(X_train)

array([[-1., -1.],
       [ 1.,  1.]])

In [37]:
#Using sklearn's built in function for standard_s

standard_scaler = preprocessing.StandardScaler()
X_ss = standard_scaler.fit_transform(X_train)
X_ss

array([[-1., -1.],
       [ 1.,  1.]])